<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\UmrahPackage;
use Illuminate\Database\Seeder;

class UmrahPackageSeeder extends Seeder
{
    public function run(): void
    {
        $packages = [
            [
                'title' => 'Economy Umrah Package 5 Star',
                'slug' => 'economy-umrah-5-star',
                'description' => 'Affordable 5-star Umrah package with premium accommodations near Haram',
                'duration_days' => 10,
                'duration_nights' => 9,
                'makkah_hotel' => 'Le Meridian Makkah',
                'makkah_hotel_stars' => 5,
                'makkah_distance_meters' => 200,
                'makkah_nights' => 5,
                'madinah_hotel' => 'Movenpick Madinah',
                'madinah_hotel_stars' => 5,
                'madinah_distance_meters' => 100,
                'madinah_nights' => 4,
                'transport_type' => 'AC Bus',
                'meal_plan' => 'breakfast',
                'inclusions' => ['Visa', 'Hotels', 'Transport', 'Guided Tours'],
                'exclusions' => ['Flights', 'Lunch', 'Dinner', 'Personal Expenses'],
                'price_quad' => 3500.00,
                'price_triple' => 4000.00,
                'price_double' => 4500.00,
                'price_single' => 5500.00,
                'child_price' => 2800.00,
                'infant_price' => 1500.00,
                'currency' => 'SAR',
                'available_seats' => 40,
                'booked_seats' => 12,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'title' => 'Premium Umrah Package 5 Star',
                'slug' => 'premium-umrah-5-star',
                'description' => 'Luxurious 5-star Umrah package with VIP services and close proximity to Haram',
                'duration_days' => 14,
                'duration_nights' => 13,
                'makkah_hotel' => 'Makkah Clock Royal Tower',
                'makkah_hotel_stars' => 5,
                'makkah_distance_meters' => 50,
                'makkah_nights' => 7,
                'madinah_hotel' => 'Pullman Zamzam Madinah',
                'madinah_hotel_stars' => 5,
                'madinah_distance_meters' => 50,
                'madinah_nights' => 6,
                'transport_type' => 'Private Van',
                'meal_plan' => 'full_board',
                'inclusions' => ['Visa', 'Hotels', 'Transport', 'Meals', 'Ziyarah Tours', 'Laundry Service'],
                'exclusions' => ['Flights', 'Personal Expenses', 'Tips'],
                'price_quad' => 5500.00,
                'price_triple' => 6200.00,
                'price_double' => 7200.00,
                'price_single' => 9500.00,
                'child_price' => 4200.00,
                'infant_price' => 2000.00,
                'currency' => 'SAR',
                'available_seats' => 20,
                'booked_seats' => 8,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'title' => 'Ramadan Umrah Special',
                'slug' => 'ramadan-umrah-special',
                'description' => 'Special Ramadan Umrah package with extended stay and special prayers',
                'duration_days' => 21,
                'duration_nights' => 20,
                'makkah_hotel' => 'Jabal Omar Hyatt Makkah',
                'makkah_hotel_stars' => 5,
                'makkah_distance_meters' => 100,
                'makkah_nights' => 10,
                'madinah_hotel' => 'Anwar Al Madinah Mövenpick',
                'madinah_hotel_stars' => 5,
                'madinah_distance_meters' => 100,
                'madinah_nights' => 10,
                'transport_type' => 'AC Bus',
                'meal_plan' => 'half_board',
                'inclusions' => ['Visa', 'Hotels', 'Transport', 'Iftar Meals', 'Taraweeh Access', 'Special Ziyarah'],
                'exclusions' => ['Flights', 'Personal Expenses', 'Shopping'],
                'price_quad' => 7500.00,
                'price_triple' => 8500.00,
                'price_double' => 10000.00,
                'price_single' => 13000.00,
                'child_price' => 5500.00,
                'infant_price' => 2500.00,
                'currency' => 'SAR',
                'available_seats' => 30,
                'booked_seats' => 25,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'title' => 'Budget Umrah Package 3 Star',
                'slug' => 'budget-umrah-3-star',
                'description' => 'Economical 3-star Umrah package for budget-conscious pilgrims',
                'duration_days' => 7,
                'duration_nights' => 6,
                'makkah_hotel' => 'Al Rawda Hotel',
                'makkah_hotel_stars' => 3,
                'makkah_distance_meters' => 500,
                'makkah_nights' => 3,
                'madinah_hotel' => 'Al Aqeeq Hotel',
                'madinah_hotel_stars' => 3,
                'madinah_distance_meters' => 400,
                'madinah_nights' => 3,
                'transport_type' => 'Shared Bus',
                'meal_plan' => 'breakfast',
                'inclusions' => ['Visa', 'Hotels', 'Transport'],
                'exclusions' => ['Meals', 'Tours', 'Personal Expenses'],
                'price_quad' => 2200.00,
                'price_triple' => 2500.00,
                'price_double' => 3000.00,
                'price_single' => 3800.00,
                'child_price' => 1800.00,
                'infant_price' => 1000.00,
                'currency' => 'SAR',
                'available_seats' => 50,
                'booked_seats' => 18,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'title' => 'VIP Umrah Package',
                'slug' => 'vip-umrah-package',
                'description' => 'Exclusive VIP Umrah experience with personal guide and luxury services',
                'duration_days' => 10,
                'duration_nights' => 9,
                'makkah_hotel' => 'Raffles Makkah Palace',
                'makkah_hotel_stars' => 5,
                'makkah_distance_meters' => 0,
                'makkah_nights' => 5,
                'madinah_hotel' => 'Four Points by Sheraton Madinah',
                'madinah_hotel_stars' => 5,
                'madinah_distance_meters' => 0,
                'madinah_nights' => 4,
                'transport_type' => 'Private Car',
                'meal_plan' => 'full_board',
                'inclusions' => ['Visa', 'Hotels', 'Transport', 'All Meals', 'Personal Guide', 'Ziarah Tours', 'Laundry', 'WiFi'],
                'exclusions' => ['Flights'],
                'price_quad' => 12000.00,
                'price_triple' => 14000.00,
                'price_double' => 16000.00,
                'price_single' => 22000.00,
                'child_price' => 9000.00,
                'infant_price' => 4000.00,
                'currency' => 'SAR',
                'available_seats' => 10,
                'booked_seats' => 3,
                'is_featured' => true,
                'status' => 'active',
            ],
        ];

        foreach ($packages as $packageData) {
            UmrahPackage::updateOrCreate(
                ['slug' => $packageData['slug']],
                $packageData
            );
        }

        $this->command->info('UmrahPackageSeeder: Created ' . count($packages) . ' sample Umrah packages.');
    }
}
